"""
Auto-generate dataConfig.js based on CSV data files in the data directory.
This script scans the data folder for files matching the pattern csvData_{yyyyMM}_age.js
and creates a configuration file with all available dates.
"""

import os
import re
from pathlib import Path

def extract_dates_from_files(data_dir):
    """Extract all unique yyyyMM dates from CSV data files."""
    dates = set()
    pattern = re.compile(r'csvData_(\d{6})_age\.js')
    
    for filename in os.listdir(data_dir):
        match = pattern.match(filename)
        if match:
            dates.add(match.group(1))
    
    return sorted(dates, reverse=True)  # Sort in descending order (newest first)

def format_date_label(yyyymm):
    """Convert yyyyMM to readable Korean format."""
    year = yyyymm[:4]
    month = yyyymm[4:6]
    return f"{year}년 {month}월"

def generate_config_file(data_dir, output_file):
    """Generate the dataConfig.js file."""
    dates = extract_dates_from_files(data_dir)
    
    if not dates:
        print("No data files found!")
        return
    
    # Build the JavaScript configuration
    config_content = """// Auto-generated data configuration
// This file lists all available data dates based on CSV files in the data directory
// Generated by generate_data_config.py

// Available data dates - automatically populated
window.availableDataDates = [
"""
    
    for date in dates:
        label = format_date_label(date)
        config_content += f"    {{ value: '{date}', label: '{label}' }},\n"
    
    config_content += """];

// Set the default/latest data date
window.currentDataDate = '""" + dates[0] + """';
"""
    
    # Write to file
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(config_content)
    
    print(f"✅ Generated {output_file}")
    print(f"📅 Found {len(dates)} data dates: {', '.join(dates)}")
    print(f"🎯 Default date set to: {dates[0]} ({format_date_label(dates[0])})")

if __name__ == "__main__":
    # Get the script's directory
    script_dir = Path(__file__).parent
    data_dir = script_dir / "data"
    output_file = data_dir / "dataConfig.js"
    
    if not data_dir.exists():
        print(f"❌ Error: Data directory not found: {data_dir}")
        exit(1)
    
    generate_config_file(data_dir, output_file)
